import { glossary } from "@/lib/glossary";

export type ExamQuestion = {
  id: string;
  domain: number;
  type: "theory" | "case";
  question: string;
  options: [string, string, string, string];
  correctIndex: number;
  explanation: string;
};

const knowledgeQuestions: ExamQuestion[] = [
  {
    id: "d1-01",
    domain: 1,
    type: "theory",
    question: "Wat is het belangrijkste doel van een informatiebeveiligingsbeleid?",
    options: [
      "Alle technische configuraties gedetailleerd voorschrijven",
      "De richting, doelstellingen en verantwoordelijkheden voor beveiliging vastleggen",
      "Alle risico's volledig elimineren",
      "Alleen voldoen aan eisen van auditors",
    ],
    correctIndex: 1,
    explanation: "Een beleid geeft bestuurlijke richting en legt verantwoordelijkheden vast. Procedures en standaarden werken dit verder uit.",
  },
  {
    id: "d1-02",
    domain: 1,
    type: "case",
    question: "Een risicoanalyse toont een kans van 20% per jaar op een incident met €100.000 schade. Wat is de annualized loss expectancy (ALE)?",
    options: ["€5.000", "€20.000", "€80.000", "€100.000"],
    correctIndex: 1,
    explanation: "ALE = single loss expectancy × annualized rate of occurrence. Dus €100.000 × 0,20 = €20.000.",
  },
  {
    id: "d1-03",
    domain: 1,
    type: "theory",
    question: "Wie is uiteindelijk verantwoordelijk voor het accepteren van een bedrijfsrisico?",
    options: ["De security engineer", "De interne auditor", "De risico-eigenaar", "De leverancier"],
    correctIndex: 2,
    explanation: "De risico-eigenaar heeft het mandaat en de verantwoordelijkheid om een risico te accepteren of behandeling te eisen.",
  },
  {
    id: "d1-04",
    domain: 1,
    type: "case",
    question: "Een organisatie sluit een cyberverzekering af voor ransomware-schade. Welke risicobehandeling is dit?",
    options: ["Vermijden", "Mitigeren", "Overdragen", "Accepteren"],
    correctIndex: 2,
    explanation: "Met een verzekering wordt een deel van de financiële impact overgedragen aan een derde partij.",
  },
  {
    id: "d1-05",
    domain: 1,
    type: "theory",
    question: "Welke ethische verplichting heeft volgens de ISC2 Code of Ethics de hoogste prioriteit?",
    options: [
      "De werkgever beschermen",
      "De professie bevorderen",
      "De samenleving, het algemeen belang en de infrastructuur beschermen",
      "Certificeringen van collega's controleren",
    ],
    correctIndex: 2,
    explanation: "De hoogste canon is het beschermen van samenleving, algemeen belang, vertrouwen en infrastructuur.",
  },
  {
    id: "d2-01",
    domain: 2,
    type: "theory",
    question: "Wie bepaalt normaal gesproken de classificatie van informatie?",
    options: ["De data-eigenaar", "De databasebeheerder", "De eindgebruiker", "De auditor"],
    correctIndex: 0,
    explanation: "De data-eigenaar bepaalt classificatie en toegangsvereisten. De data custodian voert de technische bescherming uit.",
  },
  {
    id: "d2-02",
    domain: 2,
    type: "case",
    question: "Een medewerker wil oude klantbestanden verwijderen. Wat moet eerst worden gecontroleerd?",
    options: [
      "Of de opslag bijna vol is",
      "Of bewaartermijnen en legal holds verwijdering toestaan",
      "Of de medewerker beheerrechten heeft",
      "Of de bestanden versleuteld zijn",
    ],
    correctIndex: 1,
    explanation: "Retentiebeleid, wettelijke bewaartermijnen en legal holds bepalen of data vernietigd mag worden.",
  },
  {
    id: "d2-03",
    domain: 2,
    type: "theory",
    question: "Welke methode is het meest geschikt om gegevens op een afgeschreven SSD onherstelbaar te maken?",
    options: ["Bestanden naar de prullenbak verplaatsen", "Quick format uitvoeren", "Cryptografisch wissen of fysiek vernietigen", "Bestandsnamen overschrijven"],
    correctIndex: 2,
    explanation: "Door wear leveling is traditioneel overschrijven bij SSD's onzeker. Cryptographic erase of fysieke vernietiging is geschikter.",
  },
  {
    id: "d2-04",
    domain: 2,
    type: "case",
    question: "Een rapport bevat openbare marketingdata en strikt vertrouwelijke overnameplannen. Welke classificatie krijgt het rapport?",
    options: ["De laagste classificatie", "De hoogste classificatie van de inhoud", "Gemiddeld vertrouwelijk", "Geen classificatie door gemengde inhoud"],
    correctIndex: 1,
    explanation: "Een samengesteld document erft de hoogste toepasselijke classificatie van de opgenomen informatie.",
  },
  {
    id: "d2-05",
    domain: 2,
    type: "theory",
    question: "Wat betekent data remanence?",
    options: [
      "Data die dubbel is opgeslagen",
      "Restgegevens die na een verwijderactie nog kunnen worden hersteld",
      "Data zonder eigenaar",
      "Data die de bewaartermijn overschrijdt",
    ],
    correctIndex: 1,
    explanation: "Data remanence is de achtergebleven fysieke representatie van gegevens na een verwijder- of wisactie.",
  },
  {
    id: "d3-01",
    domain: 3,
    type: "theory",
    question: "Welk beveiligingsmodel richt zich primair op vertrouwelijkheid en het voorkomen van informatiestroom naar een lager niveau?",
    options: ["Biba", "Bell-LaPadula", "Clark-Wilson", "Brewer-Nash alleen voor integriteit"],
    correctIndex: 1,
    explanation: "Bell-LaPadula beschermt vertrouwelijkheid met onder meer no read up en no write down.",
  },
  {
    id: "d3-02",
    domain: 3,
    type: "case",
    question: "Een betaalsysteem eist dat één medewerker een betaling invoert en een andere deze goedkeurt. Welk principe wordt toegepast?",
    options: ["Least privilege", "Defense in depth", "Separation of duties", "Fail open"],
    correctIndex: 2,
    explanation: "Separation of duties voorkomt dat één persoon een kritieke transactie zelfstandig kan voltooien.",
  },
  {
    id: "d3-03",
    domain: 3,
    type: "theory",
    question: "Welke eigenschap levert een digitale handtekening primair naast integriteit?",
    options: ["Beschikbaarheid", "Niet-weerlegbaarheid en authenticiteit", "Anonimiteit", "Dataminimalisatie"],
    correctIndex: 1,
    explanation: "Een digitale handtekening ondersteunt authenticiteit, integriteit en niet-weerlegbaarheid.",
  },
  {
    id: "d3-04",
    domain: 3,
    type: "case",
    question: "Een systeem moet bij een storing standaard alle toegang blokkeren. Welk ontwerpprincipe past hierbij?",
    options: ["Fail secure", "Open design", "Economy of mechanism", "Shared responsibility"],
    correctIndex: 0,
    explanation: "Fail secure betekent dat een fout of storing resulteert in een veilige, gesloten toestand.",
  },
  {
    id: "d3-05",
    domain: 3,
    type: "theory",
    question: "Wat is het verschil tussen hashing en encryptie?",
    options: [
      "Hashing is omkeerbaar, encryptie niet",
      "Hashing gebruikt altijd een publieke sleutel",
      "Hashing is een eenrichtingsfunctie, encryptie is met de juiste sleutel omkeerbaar",
      "Er is technisch geen verschil",
    ],
    correctIndex: 2,
    explanation: "Een cryptografische hash is bedoeld als eenrichtingsfunctie. Versleutelde data moet met de juiste sleutel ontsleuteld kunnen worden.",
  },
  {
    id: "d4-01",
    domain: 4,
    type: "theory",
    question: "Op welke OSI-laag werkt een traditionele router hoofdzakelijk?",
    options: ["Laag 1", "Laag 2", "Laag 3", "Laag 7"],
    correctIndex: 2,
    explanation: "Routers nemen beslissingen op basis van logische netwerkadressen en werken primair op de netwerklaag, laag 3.",
  },
  {
    id: "d4-02",
    domain: 4,
    type: "case",
    question: "Een organisatie wil voorkomen dat een gecompromitteerde werkplek direct databaseservers bereikt. Wat is de beste maatregel?",
    options: ["Een langere wachtwoordlengte", "Netwerksegmentatie met strikt gefilterde verkeersstromen", "Alleen antivirus bijwerken", "Publieke DNS uitschakelen"],
    correctIndex: 1,
    explanation: "Segmentatie en filtering beperken laterale beweging en verkleinen de impact van een gecompromitteerd segment.",
  },
  {
    id: "d4-03",
    domain: 4,
    type: "theory",
    question: "Welk protocol biedt veilige remote shell-toegang en vervangt Telnet?",
    options: ["FTP", "SNMPv1", "SSH", "TFTP"],
    correctIndex: 2,
    explanation: "SSH versleutelt authenticatie en sessieverkeer voor beheer op afstand.",
  },
  {
    id: "d4-04",
    domain: 4,
    type: "case",
    question: "Gebruikers verbinden vanaf openbare wifi met bedrijfsapplicaties. Welke maatregel beschermt data tijdens transport het best?",
    options: ["Disk-encryptie op de server", "TLS of een goed geconfigureerde VPN", "Data classificeren als intern", "MAC-adressen registreren"],
    correctIndex: 1,
    explanation: "TLS of een VPN biedt versleuteling en integriteitsbescherming voor gegevens tijdens transport.",
  },
  {
    id: "d4-05",
    domain: 4,
    type: "theory",
    question: "Wat is het centrale uitgangspunt van zero trust?",
    options: [
      "Intern verkeer is standaard vertrouwd",
      "Vertrouw alleen apparaten van het eigen merk",
      "Verifieer expliciet en geef minimale toegang ongeacht netwerklocatie",
      "Vervang firewalls door endpointbeveiliging",
    ],
    correctIndex: 2,
    explanation: "Zero trust baseert toegang niet op locatie. Elke aanvraag wordt expliciet beoordeeld met least privilege als uitgangspunt.",
  },
  {
    id: "d5-01",
    domain: 5,
    type: "theory",
    question: "Welke combinatie vormt echte multifactorauthenticatie?",
    options: ["Wachtwoord en pincode", "Vingerafdruk en gezichtsherkenning", "Smartcard en pincode", "Twee verschillende wachtwoorden"],
    correctIndex: 2,
    explanation: "Een smartcard is iets wat je hebt en een pincode iets wat je weet. De andere combinaties gebruiken één factorcategorie.",
  },
  {
    id: "d5-02",
    domain: 5,
    type: "case",
    question: "Een medewerker wisselt van financiële administratie naar marketing. Wat moet als eerste met de oude toegangsrechten gebeuren?",
    options: ["Behouden voor noodgevallen", "Direct herbeoordelen en niet meer benodigde rechten intrekken", "Na de jaarlijkse audit verwijderen", "Overdragen aan de nieuwe manager"],
    correctIndex: 1,
    explanation: "Het mover-proces vereist directe aanpassing van rechten om privilege creep te voorkomen.",
  },
  {
    id: "d5-03",
    domain: 5,
    type: "theory",
    question: "Bij welk toegangsmodel bepaalt een centrale beveiligingsclassificatie de toegang en kan de eigenaar die niet zelf wijzigen?",
    options: ["DAC", "MAC", "RBAC", "ABAC zonder beleid"],
    correctIndex: 1,
    explanation: "Mandatory Access Control gebruikt centraal beheerde labels en clearances. Gebruikers of eigenaren kunnen deze niet naar eigen inzicht aanpassen.",
  },
  {
    id: "d5-04",
    domain: 5,
    type: "case",
    question: "Een webapplicatie moet namens een gebruiker beperkte toegang krijgen tot diens cloudfoto's zonder het wachtwoord te ontvangen. Welk protocol past het best?",
    options: ["Kerberos", "OAuth 2.0", "LDAP", "RADIUS"],
    correctIndex: 1,
    explanation: "OAuth 2.0 is bedoeld voor gedelegeerde autorisatie met beperkte tokens zonder wachtwoorden te delen.",
  },
  {
    id: "d5-05",
    domain: 5,
    type: "theory",
    question: "Wat is het belangrijkste doel van periodieke access reviews?",
    options: ["Wachtwoorden langer maken", "Bevestigen dat toegekende rechten nog noodzakelijk en passend zijn", "Netwerkverkeer versnellen", "Nieuwe accounts automatisch maken"],
    correctIndex: 1,
    explanation: "Access reviews detecteren overbodige, verouderde of te ruime rechten en ondersteunen least privilege.",
  },
  {
    id: "d6-01",
    domain: 6,
    type: "theory",
    question: "Wat is het belangrijkste verschil tussen een vulnerability scan en een penetration test?",
    options: [
      "Een scan is altijd handmatig",
      "Een penetration test probeert kwetsbaarheden gecontroleerd te exploiteren",
      "Een scan vereist geen toestemming",
      "Een penetration test vindt alleen configuratiefouten",
    ],
    correctIndex: 1,
    explanation: "Een scan identificeert mogelijke zwaktes. Een pentest valideert exploiteerbaarheid en impact binnen afgesproken grenzen.",
  },
  {
    id: "d6-02",
    domain: 6,
    type: "case",
    question: "Een auditor beoordeelt een proces dat hij vorige maand zelf heeft ontworpen. Welk kernprobleem ontstaat?",
    options: ["Onvoldoende encryptie", "Gebrek aan onafhankelijkheid en objectiviteit", "Te kleine steekproef", "Onjuiste dataclassificatie"],
    correctIndex: 1,
    explanation: "Een assessor moet voldoende onafhankelijk zijn. Eigen werk beoordelen veroorzaakt een belangenconflict.",
  },
  {
    id: "d6-03",
    domain: 6,
    type: "theory",
    question: "Wat toont test coverage aan?",
    options: [
      "Dat de software foutloos is",
      "Welk deel van code, eisen of scenario's door tests wordt geraakt",
      "Dat alle risico's zijn geaccepteerd",
      "Hoeveel gebruikers de applicatie heeft",
    ],
    correctIndex: 1,
    explanation: "Coverage meet het bereik van tests. Hoge coverage bewijst niet dat er geen fouten of ontbrekende scenario's zijn.",
  },
  {
    id: "d6-04",
    domain: 6,
    type: "case",
    question: "Een kritieke kwetsbaarheid is gepatcht. Welke vervolgstap levert het beste bewijs dat het risico werkelijk is verholpen?",
    options: ["De patchnotitie archiveren", "Een gerichte hertest uitvoeren", "De eigenaar mondeling informeren", "De server hernoemen"],
    correctIndex: 1,
    explanation: "Een hertest valideert onafhankelijk dat de kwetsbaarheid niet meer reproduceerbaar is en de oplossing effectief is.",
  },
  {
    id: "d6-05",
    domain: 6,
    type: "theory",
    question: "Wanneer is een black-box test van toepassing?",
    options: [
      "De tester heeft volledige broncode en ontwerpdocumentatie",
      "De tester heeft beperkte of geen voorkennis van het doelwit",
      "Alleen unit tests worden uitgevoerd",
      "De test vindt uitsluitend in productie plaats",
    ],
    correctIndex: 1,
    explanation: "Bij black-box testing benadert de tester het systeem met weinig of geen interne kennis, vergelijkbaar met een externe aanvaller.",
  },
  {
    id: "d7-01",
    domain: 7,
    type: "theory",
    question: "Wat is tijdens incident response de eerste prioriteit wanneer mensen direct gevaar lopen?",
    options: ["Forensisch bewijs veiligstellen", "Beschikbaarheid herstellen", "Menselijke veiligheid beschermen", "De pers informeren"],
    correctIndex: 2,
    explanation: "Bescherming van mensenlevens en fysieke veiligheid gaat vóór systemen, data en bewijs.",
  },
  {
    id: "d7-02",
    domain: 7,
    type: "case",
    question: "Een server is vermoedelijk gehackt. Het team wil bewijs later juridisch kunnen gebruiken. Wat is essentieel?",
    options: ["De server direct formatteren", "Een gedocumenteerde chain of custody onderhouden", "Alle logs per e-mail versturen", "De verdachte informeren"],
    correctIndex: 1,
    explanation: "Chain of custody documenteert wie bewijs wanneer heeft verzameld, beheerd en overgedragen en ondersteunt de betrouwbaarheid ervan.",
  },
  {
    id: "d7-03",
    domain: 7,
    type: "theory",
    question: "Welke waarde beschrijft de maximaal aanvaardbare hoeveelheid dataverlies uitgedrukt in tijd?",
    options: ["MTTR", "RTO", "RPO", "SLA"],
    correctIndex: 2,
    explanation: "Recovery Point Objective bepaalt tot welk moment data hersteld moet kunnen worden en dus hoeveel dataverlies acceptabel is.",
  },
  {
    id: "d7-04",
    domain: 7,
    type: "case",
    question: "Een SOC ziet duizenden mislukte logins gevolgd door één succesvolle login vanaf hetzelfde adres. Wat is de beste eerste actie?",
    options: ["Het signaal negeren", "Het account en de bron onderzoeken en zo nodig direct beperken", "Alle auditlogs verwijderen", "De wachtwoordregels uitschakelen"],
    correctIndex: 1,
    explanation: "Dit patroon kan op brute force wijzen. Valideer het incident, beperk mogelijke schade en behoud relevante logs.",
  },
  {
    id: "d7-05",
    domain: 7,
    type: "theory",
    question: "Waarom moeten back-ups periodiek worden teruggezet in een test?",
    options: ["Om compressie te verhogen", "Om herstelbaarheid en de herstelprocedure te valideren", "Om retentie te omzeilen", "Om alle productie-incidenten te voorkomen"],
    correctIndex: 1,
    explanation: "Een geslaagde back-uptaak bewijst niet dat data bruikbaar teruggezet kan worden. Restore-tests leveren dat bewijs.",
  },
  {
    id: "d8-01",
    domain: 8,
    type: "theory",
    question: "In welke SDLC-fase is het doorgaans het goedkoopst om beveiligingseisen en threat modeling toe te passen?",
    options: ["Planning en ontwerp", "Na productie-implementatie", "Alleen tijdens incident response", "Na uitfasering"],
    correctIndex: 0,
    explanation: "Vroege beveiligingseisen en threat modeling voorkomen dure herontwerpen en reparaties later in de levenscyclus.",
  },
  {
    id: "d8-02",
    domain: 8,
    type: "case",
    question: "Een applicatie bouwt een SQL-query door gebruikersinvoer direct aan een tekenreeks toe te voegen. Welke maatregel is het meest effectief?",
    options: ["Meer logging", "Parameterized queries gebruiken", "De databasepoort wijzigen", "Uitvoer comprimeren"],
    correctIndex: 1,
    explanation: "Parameterized queries scheiden code van data en zijn een primaire verdediging tegen SQL-injectie.",
  },
  {
    id: "d8-03",
    domain: 8,
    type: "theory",
    question: "Wat is het doel van static application security testing (SAST)?",
    options: [
      "Een draaiende applicatie via netwerkverkeer testen",
      "Broncode of gecompileerde code analyseren zonder de applicatie uit te voeren",
      "Alleen open-source licenties controleren",
      "Productiegebruikers monitoren",
    ],
    correctIndex: 1,
    explanation: "SAST analyseert code of binaries zonder de applicatie als actief systeem te benaderen.",
  },
  {
    id: "d8-04",
    domain: 8,
    type: "case",
    question: "Een team neemt een populaire open-source bibliotheek op. Welke actie beheerst supply-chainrisico het best?",
    options: [
      "Alleen de downloadteller controleren",
      "Versie vastzetten, herkomst verifiëren en continu op kwetsbaarheden scannen",
      "De bibliotheek nooit bijwerken",
      "De naam van het pakket wijzigen",
    ],
    correctIndex: 1,
    explanation: "Herkomstcontrole, dependency locking, inventarisatie en continue kwetsbaarheidsbewaking beperken software supply-chainrisico.",
  },
  {
    id: "d8-05",
    domain: 8,
    type: "theory",
    question: "Welke test richt zich op een draaiende webapplicatie zonder de broncode rechtstreeks te analyseren?",
    options: ["SAST", "DAST", "Code review", "Compiler linting"],
    correctIndex: 1,
    explanation: "Dynamic Application Security Testing test de actieve applicatie van buitenaf via de beschikbare interfaces.",
  },
  {
    id: "d1-06",
    domain: 1,
    type: "case",
    question: "Een nieuw beveiligingsbeleid is goedgekeurd. Wat is de beste volgende stap?",
    options: ["Alle oude procedures verwijderen", "Het beleid communiceren en vertalen naar standaarden en procedures", "Alle risico's accepteren", "Alleen de auditor informeren"],
    correctIndex: 1,
    explanation: "Een goedgekeurd beleid moet worden geïmplementeerd via communicatie, standaarden, procedures, training en controle.",
  },
  {
    id: "d1-07",
    domain: 1,
    type: "theory",
    question: "Wat is het verschil tussen due care en due diligence?",
    options: ["Er is geen verschil", "Due care kiest passende maatregelen, due diligence controleert voortdurend of ze werken", "Due diligence geldt alleen voor techniek", "Due care geldt alleen na incidenten"],
    correctIndex: 1,
    explanation: "Due care gaat over redelijk en zorgvuldig handelen. Due diligence gaat over blijvend onderzoeken, controleren en verbeteren.",
  },
  {
    id: "d1-08",
    domain: 1,
    type: "case",
    question: "Een leverancier verwerkt persoonsgegevens namens de organisatie. Wie blijft eindverantwoordelijk voor passende bescherming?",
    options: ["Alleen de leverancier", "De organisatie als verwerkingsverantwoordelijke", "De eindgebruiker", "De internetprovider"],
    correctIndex: 1,
    explanation: "Uitbesteding draagt werkzaamheden over, maar niet de bestuurlijke verantwoordelijkheid en verantwoordingsplicht.",
  },
  {
    id: "d1-09",
    domain: 1,
    type: "theory",
    question: "Welke analyse bepaalt welke bedrijfsprocessen kritiek zijn en welke gevolgen uitval heeft?",
    options: ["BIA", "SAST", "Gap scan", "Chain of custody"],
    correctIndex: 0,
    explanation: "Een Business Impact Analysis identificeert kritieke processen, afhankelijkheden en de gevolgen van verstoring.",
  },
  {
    id: "d1-10",
    domain: 1,
    type: "case",
    question: "De kosten van een controle zijn hoger dan de verwachte schade, maar wetgeving verplicht de controle. Wat moet de organisatie doen?",
    options: ["De controle overslaan", "De controle implementeren", "Het risico stilzwijgend accepteren", "De wet negeren na documentatie"],
    correctIndex: 1,
    explanation: "Verplichte wettelijke controles zijn geen zuiver economische keuze en moeten worden geïmplementeerd.",
  },
  {
    id: "d2-06",
    domain: 2,
    type: "theory",
    question: "Wat is het doel van dataminimalisatie?",
    options: ["Alle data comprimeren", "Alleen gegevens verzamelen en bewaren die noodzakelijk zijn", "Data onbeperkt bewaren", "Alle data openbaar maken"],
    correctIndex: 1,
    explanation: "Dataminimalisatie beperkt verzameling, verwerking en retentie tot wat voor het doel noodzakelijk is.",
  },
  {
    id: "d2-07",
    domain: 2,
    type: "case",
    question: "Een back-up bevat vertrouwelijke productiegegevens. Welke classificatie moet de back-up krijgen?",
    options: ["Altijd openbaar", "Dezelfde passende classificatie en bescherming als de brondata", "Geen classificatie", "Alleen intern als hij offline staat"],
    correctIndex: 1,
    explanation: "Kopieën en back-ups behouden de gevoeligheid van de oorspronkelijke gegevens.",
  },
  {
    id: "d2-08",
    domain: 2,
    type: "theory",
    question: "Welke rol beheert data technisch namens de data-eigenaar?",
    options: ["Data custodian", "Risk owner", "Auditor", "Privacy subject"],
    correctIndex: 0,
    explanation: "De data custodian implementeert opslag, back-up en technische controles volgens instructies van de eigenaar.",
  },
  {
    id: "d2-09",
    domain: 2,
    type: "case",
    question: "Een database wordt gebruikt voor een testomgeving. Wat is de beste bescherming voor echte klantgegevens?",
    options: ["De ontwikkelaars geheimhouding laten beloven", "Data maskeren of synthetische testdata gebruiken", "De testserver hernoemen", "Alle logging uitschakelen"],
    correctIndex: 1,
    explanation: "Masking en synthetische data beperken blootstelling van persoonsgegevens buiten productie.",
  },
  {
    id: "d2-10",
    domain: 2,
    type: "theory",
    question: "In welke fase van de datalevenscyclus hoort gecontroleerde vernietiging?",
    options: ["Create", "Use", "Share", "Dispose"],
    correctIndex: 3,
    explanation: "In de disposefase worden gegevens volgens retentie- en vernietigingsregels veilig verwijderd.",
  },
  {
    id: "d3-06",
    domain: 3,
    type: "theory",
    question: "Welk model richt zich primair op integriteit met no read down en no write up?",
    options: ["Biba", "Bell-LaPadula", "Kerberos", "OAuth"],
    correctIndex: 0,
    explanation: "Het Biba-model beschermt integriteit door informatiestromen van lagere naar hogere integriteitsniveaus te beperken.",
  },
  {
    id: "d3-07",
    domain: 3,
    type: "case",
    question: "Een organisatie bewaart encryptiesleutels op dezelfde server als de versleutelde database. Wat is de grootste zwakte?",
    options: ["De database wordt te snel", "Een compromis kan zowel data als sleutels blootleggen", "Hashing stopt met werken", "Back-ups worden onmogelijk"],
    correctIndex: 1,
    explanation: "Sleutels moeten gescheiden en streng beheerd worden, bijvoorbeeld met een KMS of HSM.",
  },
  {
    id: "d3-08",
    domain: 3,
    type: "theory",
    question: "Wat biedt een HSM?",
    options: ["Fysiek beschermde generatie en opslag van cryptografische sleutels", "Snellere DNS", "Netwerksegmentatie", "Dataclassificatie"],
    correctIndex: 0,
    explanation: "Een Hardware Security Module beschermt cryptografische operaties en sleutelmateriaal in een gehard apparaat.",
  },
  {
    id: "d3-09",
    domain: 3,
    type: "case",
    question: "Twee datacenters draaien gelijktijdig en kunnen direct verkeer overnemen. Welke beschikbaarheidsstrategie is dit?",
    options: ["Cold site", "Active-active redundantie", "Tape rotation", "Fail open"],
    correctIndex: 1,
    explanation: "Bij active-active verwerken meerdere locaties actief verkeer en kunnen zij uitval direct opvangen.",
  },
  {
    id: "d3-10",
    domain: 3,
    type: "theory",
    question: "Waarom wordt een salt aan wachtwoordhashes toegevoegd?",
    options: ["Om wachtwoorden korter te maken", "Om vooraf berekende tabellen en gelijke hashes te bemoeilijken", "Om encryptie omkeerbaar te maken", "Om MFA te vervangen"],
    correctIndex: 1,
    explanation: "Een unieke salt zorgt dat gelijke wachtwoorden verschillende hashes krijgen en beperkt rainbow-tableaanvallen.",
  },
  {
    id: "d4-06",
    domain: 4,
    type: "theory",
    question: "Welk systeem detecteert verdacht netwerkverkeer maar blokkeert het normaal niet automatisch?",
    options: ["NIDS", "NIPS", "Proxy firewall", "Load balancer"],
    correctIndex: 0,
    explanation: "Een NIDS detecteert en alarmeert. Een inline NIPS kan verkeer actief blokkeren.",
  },
  {
    id: "d4-07",
    domain: 4,
    type: "case",
    question: "Een aanvaller stuurt vervalste ARP-antwoorden op een lokaal netwerk. Welke aanval probeert hij uit te voeren?",
    options: ["ARP poisoning", "DNSSEC validation", "SQL injection", "Pass-the-hash"],
    correctIndex: 0,
    explanation: "ARP poisoning koppelt het adres van de aanvaller aan een ander IP-adres en kan man-in-the-middleverkeer mogelijk maken.",
  },
  {
    id: "d4-08",
    domain: 4,
    type: "theory",
    question: "Wat is het beveiligingsvoordeel van DNSSEC?",
    options: ["Het versleutelt alle DNS-vragen", "Het valideert authenticiteit en integriteit van DNS-antwoorden", "Het verbergt IP-adressen", "Het vervangt TLS"],
    correctIndex: 1,
    explanation: "DNSSEC gebruikt digitale handtekeningen om vervalste of gewijzigde DNS-data te detecteren.",
  },
  {
    id: "d4-09",
    domain: 4,
    type: "case",
    question: "Een publieke webserver moet bereikbaar zijn zonder directe toegang tot het interne netwerk. Waar hoort deze server?",
    options: ["In hetzelfde VLAN als werkplekken", "In een DMZ met beperkte verbindingen", "Op een onbeveiligd gastnetwerk", "Op de databasecluster"],
    correctIndex: 1,
    explanation: "Een DMZ isoleert publiek bereikbare diensten en staat alleen noodzakelijke verkeersstromen toe.",
  },
  {
    id: "d4-10",
    domain: 4,
    type: "theory",
    question: "Welke draadloze beveiligingsstandaard heeft voor moderne bedrijfsnetwerken de voorkeur?",
    options: ["WEP", "WPA", "WPA2 met TKIP", "WPA3-Enterprise"],
    correctIndex: 3,
    explanation: "WPA3-Enterprise biedt moderne cryptografie en centrale bedrijfsauthenticatie.",
  },
  {
    id: "d5-06",
    domain: 5,
    type: "theory",
    question: "Welke stap komt na identificatie en authenticatie?",
    options: ["Autorisatie", "Encryptie", "Classificatie", "Back-up"],
    correctIndex: 0,
    explanation: "Na vaststelling van de identiteit bepaalt autorisatie welke acties en bronnen zijn toegestaan.",
  },
  {
    id: "d5-07",
    domain: 5,
    type: "case",
    question: "Toegang wordt bepaald door rol, locatie, apparaattype en tijdstip. Welk model past het best?",
    options: ["DAC", "RBAC zonder context", "ABAC", "MAC met één label"],
    correctIndex: 2,
    explanation: "Attribute-Based Access Control evalueert meerdere kenmerken van gebruiker, bron, actie en omgeving.",
  },
  {
    id: "d5-08",
    domain: 5,
    type: "theory",
    question: "Wat is privilege creep?",
    options: ["Het geleidelijk opstapelen van niet meer benodigde rechten", "Een sterke vorm van MFA", "Automatische accountverwijdering", "Versleuteling van rollen"],
    correctIndex: 0,
    explanation: "Privilege creep ontstaat wanneer rechten bij functiewijzigingen worden toegevoegd maar oude rechten niet worden ingetrokken.",
  },
  {
    id: "d5-09",
    domain: 5,
    type: "case",
    question: "Een beheerder heeft tijdelijk roottoegang nodig voor onderhoud. Wat is de beste aanpak?",
    options: ["Een permanent gedeeld rootaccount", "Just-in-timetoegang met goedkeuring en logging", "Het wachtwoord per e-mail sturen", "Alle controles uitschakelen"],
    correctIndex: 1,
    explanation: "Just-in-time privileged access beperkt duur, vereist controle en levert een audittrail.",
  },
  {
    id: "d5-10",
    domain: 5,
    type: "theory",
    question: "Waarvoor wordt SAML meestal gebruikt?",
    options: ["Federatieve authenticatie en single sign-on", "Disk-encryptie", "Netwerkroutering", "Vulnerability scanning"],
    correctIndex: 0,
    explanation: "SAML wisselt ondertekende identity assertions uit tussen identity provider en service provider.",
  },
  {
    id: "d6-06",
    domain: 6,
    type: "theory",
    question: "Wat is een belangrijk voordeel van geautomatiseerde security regression tests?",
    options: ["Ze maken handmatige tests altijd overbodig", "Ze detecteren terugkerende kwetsbaarheden na wijzigingen", "Ze accepteren automatisch risico's", "Ze vervangen requirements"],
    correctIndex: 1,
    explanation: "Regression tests controleren herhaalbaar of eerder opgeloste beveiligingsproblemen terugkeren.",
  },
  {
    id: "d6-07",
    domain: 6,
    type: "case",
    question: "Een pentester ontdekt buiten de afgesproken scope een mogelijk kritisch systeem. Wat moet hij doen?",
    options: ["Het systeem direct exploiteren", "Stoppen en toestemming of scopeverduidelijking vragen", "De bevinding openbaar maken", "Alle logs wissen"],
    correctIndex: 1,
    explanation: "Rules of engagement en scope zijn bindend. Buiten scope testen vereist voorafgaande expliciete toestemming.",
  },
  {
    id: "d6-08",
    domain: 6,
    type: "theory",
    question: "Wat is het doel van een audit trail?",
    options: ["Systeemacties herleidbaar en controleerbaar maken", "Alle data anonimiseren", "Netwerkbandbreedte verhogen", "Risico's verwijderen"],
    correctIndex: 0,
    explanation: "Een audit trail ondersteunt accountability, reconstructie en controle door relevante gebeurtenissen vast te leggen.",
  },
  {
    id: "d6-09",
    domain: 6,
    type: "case",
    question: "Een scan rapporteert een kwetsbaarheid die na handmatige controle niet bestaat. Hoe heet dit?",
    options: ["True positive", "False positive", "False negative", "Accepted risk"],
    correctIndex: 1,
    explanation: "Een false positive is een gemelde bevinding die in werkelijkheid niet aanwezig is.",
  },
  {
    id: "d6-10",
    domain: 6,
    type: "theory",
    question: "Welke testmethode combineert beperkte interne kennis met een externe aanvalsperspectief?",
    options: ["White box", "Gray box", "Black box zonder kennis", "Unit test"],
    correctIndex: 1,
    explanation: "Gray-box testing gebruikt gedeeltelijke kennis en combineert eigenschappen van black-box en white-box testing.",
  },
  {
    id: "d7-06",
    domain: 7,
    type: "theory",
    question: "Welke incidentresponsfase volgt meestal direct op detectie en analyse?",
    options: ["Containment", "Lessons learned", "Archivering", "Risicoacceptatie"],
    correctIndex: 0,
    explanation: "Na analyse wordt het incident ingeperkt om verdere schade te voorkomen, gevolgd door eradication en recovery.",
  },
  {
    id: "d7-07",
    domain: 7,
    type: "case",
    question: "Malware draait in het geheugen van een server. Welk bewijs moet als eerste worden verzameld?",
    options: ["Papieren handleidingen", "Volatiele geheugendata", "Oude tapes", "De inventarislijst"],
    correctIndex: 1,
    explanation: "Volgens de order of volatility moet vluchtige data zoals RAM vroeg worden veiliggesteld.",
  },
  {
    id: "d7-08",
    domain: 7,
    type: "theory",
    question: "Wat beschrijft de RTO?",
    options: ["Maximaal acceptabel dataverlies", "Maximaal acceptabele hersteltijd", "Gemiddelde tijd tussen storingen", "Bewaartermijn van logs"],
    correctIndex: 1,
    explanation: "Recovery Time Objective bepaalt hoe snel een dienst na verstoring hersteld moet zijn.",
  },
  {
    id: "d7-09",
    domain: 7,
    type: "case",
    question: "Een hot site is volledig ingericht en snel inzetbaar. Wat is het belangrijkste nadeel?",
    options: ["Lange hersteltijd", "Hoge kosten", "Geen netwerkverbinding", "Geen apparatuur"],
    correctIndex: 1,
    explanation: "Een hot site biedt snelle recovery maar kost veel door continue infrastructuur, data en beheer.",
  },
  {
    id: "d7-10",
    domain: 7,
    type: "theory",
    question: "Wat is het doel van job rotation in beveiligingsoperaties?",
    options: ["Fraude detecteren en afhankelijkheid van één persoon beperken", "Alle rechten permanent uitbreiden", "Logging vervangen", "Back-ups versnellen"],
    correctIndex: 0,
    explanation: "Functieroulatie kan verborgen fraude zichtbaar maken en kennis- en sleutelpersoonrisico verminderen.",
  },
  {
    id: "d8-06",
    domain: 8,
    type: "theory",
    question: "Welke techniek voorkomt dat onbetrouwbare uitvoer als script in een browser wordt uitgevoerd?",
    options: ["Contextafhankelijke output encoding", "Database-indexering", "Load balancing", "Disk partitioning"],
    correctIndex: 0,
    explanation: "Contextafhankelijke output encoding is een primaire maatregel tegen cross-site scripting.",
  },
  {
    id: "d8-07",
    domain: 8,
    type: "case",
    question: "Een API controleert alleen of een gebruiker is ingelogd, niet of hij het gevraagde klantrecord mag zien. Welke kwetsbaarheid ontstaat?",
    options: ["Broken object level authorization", "Buffer overflow", "DNS poisoning", "Race-free design"],
    correctIndex: 0,
    explanation: "Objectniveau-autorisatie moet bij iedere aanvraag controleren of de gebruiker toegang heeft tot precies dat object.",
  },
  {
    id: "d8-08",
    domain: 8,
    type: "theory",
    question: "Wat beschrijft een SBOM?",
    options: ["De softwarecomponenten en afhankelijkheden in een product", "Alle gebruikersrollen", "Netwerkroutes", "Alle incidenten"],
    correctIndex: 0,
    explanation: "Een Software Bill of Materials inventariseert componenten en versies voor supply-chainbeheer en kwetsbaarheidsanalyse.",
  },
  {
    id: "d8-09",
    domain: 8,
    type: "case",
    question: "Een geheim staat per ongeluk in een Git-repository. Wat is de eerste noodzakelijke herstelactie?",
    options: ["Alleen het bestand verwijderen", "Het geheim intrekken of roteren en daarna de blootstelling onderzoeken", "De repository hernoemen", "Logging uitschakelen"],
    correctIndex: 1,
    explanation: "Een gepubliceerd geheim moet als gecompromitteerd worden behandeld. Rotatie of intrekking is noodzakelijk.",
  },
  {
    id: "d8-10",
    domain: 8,
    type: "theory",
    question: "Waarom worden security checks vroeg in CI/CD geplaatst?",
    options: ["Om kwetsbaarheden eerder en goedkoper te vinden", "Om code reviews te verbieden", "Om productie direct te wijzigen", "Om requirements overbodig te maken"],
    correctIndex: 0,
    explanation: "Shift left geeft ontwikkelaars snelle feedback en verlaagt herstelkosten voordat software productie bereikt.",
  },
];

export const EXAM_QUESTION_COUNT = 40;
export const GLOSSARY_QUESTION_COUNT = glossary.length;

export const glossaryQuestions: ExamQuestion[] = glossary.map((term, termIndex) => {
  const sameDomain = glossary.filter((candidate) => candidate.domain === term.domain);
  const distractors = [1, 7, 19].map(
    (offset) => sameDomain[(sameDomain.indexOf(term) + offset) % sameDomain.length],
  );
  const correctIndex = termIndex % 4;
  const definitions = distractors.map((candidate) => candidate.definitionNl);
  definitions.splice(correctIndex, 0, term.definitionNl);
  return {
    id: `term-${term.id}`,
    domain: term.domain,
    type: "theory",
    question: `Welke definitie hoort bij het begrip “${term.termNl}”?`,
    options: definitions as [string, string, string, string],
    correctIndex,
    explanation: `${term.termNl}: ${term.definitionNl}`,
  };
});

export const examQuestions = [...knowledgeQuestions, ...glossaryQuestions];
export const PRACTICE_QUESTION_COUNT = 24;

export function calculateExamScore(
  answers: Record<string, number>,
  questionIds = examQuestions.map((question) => question.id),
) {
  const selectedIds = new Set(questionIds);
  return examQuestions.reduce(
    (score, question) =>
      score + (selectedIds.has(question.id) && answers[question.id] === question.correctIndex ? 1 : 0),
    0,
  );
}
