export type ExamQuestion = {
  id: string;
  domain: number;
  type: "theory" | "case";
  question: string;
  options: [string, string, string, string];
  correctIndex: number;
  explanation: string;
};

export const examQuestions: ExamQuestion[] = [
  {
    id: "d1-01",
    domain: 1,
    type: "theory",
    question: "Wat is het belangrijkste doel van een informatiebeveiligingsbeleid?",
    options: [
      "Alle technische configuraties gedetailleerd voorschrijven",
      "De richting, doelstellingen en verantwoordelijkheden voor beveiliging vastleggen",
      "Alle risico's volledig elimineren",
      "Alleen voldoen aan eisen van auditors",
    ],
    correctIndex: 1,
    explanation: "Een beleid geeft bestuurlijke richting en legt verantwoordelijkheden vast. Procedures en standaarden werken dit verder uit.",
  },
  {
    id: "d1-02",
    domain: 1,
    type: "case",
    question: "Een risicoanalyse toont een kans van 20% per jaar op een incident met €100.000 schade. Wat is de annualized loss expectancy (ALE)?",
    options: ["€5.000", "€20.000", "€80.000", "€100.000"],
    correctIndex: 1,
    explanation: "ALE = single loss expectancy × annualized rate of occurrence. Dus €100.000 × 0,20 = €20.000.",
  },
  {
    id: "d1-03",
    domain: 1,
    type: "theory",
    question: "Wie is uiteindelijk verantwoordelijk voor het accepteren van een bedrijfsrisico?",
    options: ["De security engineer", "De interne auditor", "De risico-eigenaar", "De leverancier"],
    correctIndex: 2,
    explanation: "De risico-eigenaar heeft het mandaat en de verantwoordelijkheid om een risico te accepteren of behandeling te eisen.",
  },
  {
    id: "d1-04",
    domain: 1,
    type: "case",
    question: "Een organisatie sluit een cyberverzekering af voor ransomware-schade. Welke risicobehandeling is dit?",
    options: ["Vermijden", "Mitigeren", "Overdragen", "Accepteren"],
    correctIndex: 2,
    explanation: "Met een verzekering wordt een deel van de financiële impact overgedragen aan een derde partij.",
  },
  {
    id: "d1-05",
    domain: 1,
    type: "theory",
    question: "Welke ethische verplichting heeft volgens de ISC2 Code of Ethics de hoogste prioriteit?",
    options: [
      "De werkgever beschermen",
      "De professie bevorderen",
      "De samenleving, het algemeen belang en de infrastructuur beschermen",
      "Certificeringen van collega's controleren",
    ],
    correctIndex: 2,
    explanation: "De hoogste canon is het beschermen van samenleving, algemeen belang, vertrouwen en infrastructuur.",
  },
  {
    id: "d2-01",
    domain: 2,
    type: "theory",
    question: "Wie bepaalt normaal gesproken de classificatie van informatie?",
    options: ["De data-eigenaar", "De databasebeheerder", "De eindgebruiker", "De auditor"],
    correctIndex: 0,
    explanation: "De data-eigenaar bepaalt classificatie en toegangsvereisten. De data custodian voert de technische bescherming uit.",
  },
  {
    id: "d2-02",
    domain: 2,
    type: "case",
    question: "Een medewerker wil oude klantbestanden verwijderen. Wat moet eerst worden gecontroleerd?",
    options: [
      "Of de opslag bijna vol is",
      "Of bewaartermijnen en legal holds verwijdering toestaan",
      "Of de medewerker beheerrechten heeft",
      "Of de bestanden versleuteld zijn",
    ],
    correctIndex: 1,
    explanation: "Retentiebeleid, wettelijke bewaartermijnen en legal holds bepalen of data vernietigd mag worden.",
  },
  {
    id: "d2-03",
    domain: 2,
    type: "theory",
    question: "Welke methode is het meest geschikt om gegevens op een afgeschreven SSD onherstelbaar te maken?",
    options: ["Bestanden naar de prullenbak verplaatsen", "Quick format uitvoeren", "Cryptografisch wissen of fysiek vernietigen", "Bestandsnamen overschrijven"],
    correctIndex: 2,
    explanation: "Door wear leveling is traditioneel overschrijven bij SSD's onzeker. Cryptographic erase of fysieke vernietiging is geschikter.",
  },
  {
    id: "d2-04",
    domain: 2,
    type: "case",
    question: "Een rapport bevat openbare marketingdata en strikt vertrouwelijke overnameplannen. Welke classificatie krijgt het rapport?",
    options: ["De laagste classificatie", "De hoogste classificatie van de inhoud", "Gemiddeld vertrouwelijk", "Geen classificatie door gemengde inhoud"],
    correctIndex: 1,
    explanation: "Een samengesteld document erft de hoogste toepasselijke classificatie van de opgenomen informatie.",
  },
  {
    id: "d2-05",
    domain: 2,
    type: "theory",
    question: "Wat betekent data remanence?",
    options: [
      "Data die dubbel is opgeslagen",
      "Restgegevens die na een verwijderactie nog kunnen worden hersteld",
      "Data zonder eigenaar",
      "Data die de bewaartermijn overschrijdt",
    ],
    correctIndex: 1,
    explanation: "Data remanence is de achtergebleven fysieke representatie van gegevens na een verwijder- of wisactie.",
  },
  {
    id: "d3-01",
    domain: 3,
    type: "theory",
    question: "Welk beveiligingsmodel richt zich primair op vertrouwelijkheid en het voorkomen van informatiestroom naar een lager niveau?",
    options: ["Biba", "Bell-LaPadula", "Clark-Wilson", "Brewer-Nash alleen voor integriteit"],
    correctIndex: 1,
    explanation: "Bell-LaPadula beschermt vertrouwelijkheid met onder meer no read up en no write down.",
  },
  {
    id: "d3-02",
    domain: 3,
    type: "case",
    question: "Een betaalsysteem eist dat één medewerker een betaling invoert en een andere deze goedkeurt. Welk principe wordt toegepast?",
    options: ["Least privilege", "Defense in depth", "Separation of duties", "Fail open"],
    correctIndex: 2,
    explanation: "Separation of duties voorkomt dat één persoon een kritieke transactie zelfstandig kan voltooien.",
  },
  {
    id: "d3-03",
    domain: 3,
    type: "theory",
    question: "Welke eigenschap levert een digitale handtekening primair naast integriteit?",
    options: ["Beschikbaarheid", "Niet-weerlegbaarheid en authenticiteit", "Anonimiteit", "Dataminimalisatie"],
    correctIndex: 1,
    explanation: "Een digitale handtekening ondersteunt authenticiteit, integriteit en niet-weerlegbaarheid.",
  },
  {
    id: "d3-04",
    domain: 3,
    type: "case",
    question: "Een systeem moet bij een storing standaard alle toegang blokkeren. Welk ontwerpprincipe past hierbij?",
    options: ["Fail secure", "Open design", "Economy of mechanism", "Shared responsibility"],
    correctIndex: 0,
    explanation: "Fail secure betekent dat een fout of storing resulteert in een veilige, gesloten toestand.",
  },
  {
    id: "d3-05",
    domain: 3,
    type: "theory",
    question: "Wat is het verschil tussen hashing en encryptie?",
    options: [
      "Hashing is omkeerbaar, encryptie niet",
      "Hashing gebruikt altijd een publieke sleutel",
      "Hashing is een eenrichtingsfunctie, encryptie is met de juiste sleutel omkeerbaar",
      "Er is technisch geen verschil",
    ],
    correctIndex: 2,
    explanation: "Een cryptografische hash is bedoeld als eenrichtingsfunctie. Versleutelde data moet met de juiste sleutel ontsleuteld kunnen worden.",
  },
  {
    id: "d4-01",
    domain: 4,
    type: "theory",
    question: "Op welke OSI-laag werkt een traditionele router hoofdzakelijk?",
    options: ["Laag 1", "Laag 2", "Laag 3", "Laag 7"],
    correctIndex: 2,
    explanation: "Routers nemen beslissingen op basis van logische netwerkadressen en werken primair op de netwerklaag, laag 3.",
  },
  {
    id: "d4-02",
    domain: 4,
    type: "case",
    question: "Een organisatie wil voorkomen dat een gecompromitteerde werkplek direct databaseservers bereikt. Wat is de beste maatregel?",
    options: ["Een langere wachtwoordlengte", "Netwerksegmentatie met strikt gefilterde verkeersstromen", "Alleen antivirus bijwerken", "Publieke DNS uitschakelen"],
    correctIndex: 1,
    explanation: "Segmentatie en filtering beperken laterale beweging en verkleinen de impact van een gecompromitteerd segment.",
  },
  {
    id: "d4-03",
    domain: 4,
    type: "theory",
    question: "Welk protocol biedt veilige remote shell-toegang en vervangt Telnet?",
    options: ["FTP", "SNMPv1", "SSH", "TFTP"],
    correctIndex: 2,
    explanation: "SSH versleutelt authenticatie en sessieverkeer voor beheer op afstand.",
  },
  {
    id: "d4-04",
    domain: 4,
    type: "case",
    question: "Gebruikers verbinden vanaf openbare wifi met bedrijfsapplicaties. Welke maatregel beschermt data tijdens transport het best?",
    options: ["Disk-encryptie op de server", "TLS of een goed geconfigureerde VPN", "Data classificeren als intern", "MAC-adressen registreren"],
    correctIndex: 1,
    explanation: "TLS of een VPN biedt versleuteling en integriteitsbescherming voor gegevens tijdens transport.",
  },
  {
    id: "d4-05",
    domain: 4,
    type: "theory",
    question: "Wat is het centrale uitgangspunt van zero trust?",
    options: [
      "Intern verkeer is standaard vertrouwd",
      "Vertrouw alleen apparaten van het eigen merk",
      "Verifieer expliciet en geef minimale toegang ongeacht netwerklocatie",
      "Vervang firewalls door endpointbeveiliging",
    ],
    correctIndex: 2,
    explanation: "Zero trust baseert toegang niet op locatie. Elke aanvraag wordt expliciet beoordeeld met least privilege als uitgangspunt.",
  },
  {
    id: "d5-01",
    domain: 5,
    type: "theory",
    question: "Welke combinatie vormt echte multifactorauthenticatie?",
    options: ["Wachtwoord en pincode", "Vingerafdruk en gezichtsherkenning", "Smartcard en pincode", "Twee verschillende wachtwoorden"],
    correctIndex: 2,
    explanation: "Een smartcard is iets wat je hebt en een pincode iets wat je weet. De andere combinaties gebruiken één factorcategorie.",
  },
  {
    id: "d5-02",
    domain: 5,
    type: "case",
    question: "Een medewerker wisselt van financiële administratie naar marketing. Wat moet als eerste met de oude toegangsrechten gebeuren?",
    options: ["Behouden voor noodgevallen", "Direct herbeoordelen en niet meer benodigde rechten intrekken", "Na de jaarlijkse audit verwijderen", "Overdragen aan de nieuwe manager"],
    correctIndex: 1,
    explanation: "Het mover-proces vereist directe aanpassing van rechten om privilege creep te voorkomen.",
  },
  {
    id: "d5-03",
    domain: 5,
    type: "theory",
    question: "Bij welk toegangsmodel bepaalt een centrale beveiligingsclassificatie de toegang en kan de eigenaar die niet zelf wijzigen?",
    options: ["DAC", "MAC", "RBAC", "ABAC zonder beleid"],
    correctIndex: 1,
    explanation: "Mandatory Access Control gebruikt centraal beheerde labels en clearances. Gebruikers of eigenaren kunnen deze niet naar eigen inzicht aanpassen.",
  },
  {
    id: "d5-04",
    domain: 5,
    type: "case",
    question: "Een webapplicatie moet namens een gebruiker beperkte toegang krijgen tot diens cloudfoto's zonder het wachtwoord te ontvangen. Welk protocol past het best?",
    options: ["Kerberos", "OAuth 2.0", "LDAP", "RADIUS"],
    correctIndex: 1,
    explanation: "OAuth 2.0 is bedoeld voor gedelegeerde autorisatie met beperkte tokens zonder wachtwoorden te delen.",
  },
  {
    id: "d5-05",
    domain: 5,
    type: "theory",
    question: "Wat is het belangrijkste doel van periodieke access reviews?",
    options: ["Wachtwoorden langer maken", "Bevestigen dat toegekende rechten nog noodzakelijk en passend zijn", "Netwerkverkeer versnellen", "Nieuwe accounts automatisch maken"],
    correctIndex: 1,
    explanation: "Access reviews detecteren overbodige, verouderde of te ruime rechten en ondersteunen least privilege.",
  },
  {
    id: "d6-01",
    domain: 6,
    type: "theory",
    question: "Wat is het belangrijkste verschil tussen een vulnerability scan en een penetration test?",
    options: [
      "Een scan is altijd handmatig",
      "Een penetration test probeert kwetsbaarheden gecontroleerd te exploiteren",
      "Een scan vereist geen toestemming",
      "Een penetration test vindt alleen configuratiefouten",
    ],
    correctIndex: 1,
    explanation: "Een scan identificeert mogelijke zwaktes. Een pentest valideert exploiteerbaarheid en impact binnen afgesproken grenzen.",
  },
  {
    id: "d6-02",
    domain: 6,
    type: "case",
    question: "Een auditor beoordeelt een proces dat hij vorige maand zelf heeft ontworpen. Welk kernprobleem ontstaat?",
    options: ["Onvoldoende encryptie", "Gebrek aan onafhankelijkheid en objectiviteit", "Te kleine steekproef", "Onjuiste dataclassificatie"],
    correctIndex: 1,
    explanation: "Een assessor moet voldoende onafhankelijk zijn. Eigen werk beoordelen veroorzaakt een belangenconflict.",
  },
  {
    id: "d6-03",
    domain: 6,
    type: "theory",
    question: "Wat toont test coverage aan?",
    options: [
      "Dat de software foutloos is",
      "Welk deel van code, eisen of scenario's door tests wordt geraakt",
      "Dat alle risico's zijn geaccepteerd",
      "Hoeveel gebruikers de applicatie heeft",
    ],
    correctIndex: 1,
    explanation: "Coverage meet het bereik van tests. Hoge coverage bewijst niet dat er geen fouten of ontbrekende scenario's zijn.",
  },
  {
    id: "d6-04",
    domain: 6,
    type: "case",
    question: "Een kritieke kwetsbaarheid is gepatcht. Welke vervolgstap levert het beste bewijs dat het risico werkelijk is verholpen?",
    options: ["De patchnotitie archiveren", "Een gerichte hertest uitvoeren", "De eigenaar mondeling informeren", "De server hernoemen"],
    correctIndex: 1,
    explanation: "Een hertest valideert onafhankelijk dat de kwetsbaarheid niet meer reproduceerbaar is en de oplossing effectief is.",
  },
  {
    id: "d6-05",
    domain: 6,
    type: "theory",
    question: "Wanneer is een black-box test van toepassing?",
    options: [
      "De tester heeft volledige broncode en ontwerpdocumentatie",
      "De tester heeft beperkte of geen voorkennis van het doelwit",
      "Alleen unit tests worden uitgevoerd",
      "De test vindt uitsluitend in productie plaats",
    ],
    correctIndex: 1,
    explanation: "Bij black-box testing benadert de tester het systeem met weinig of geen interne kennis, vergelijkbaar met een externe aanvaller.",
  },
  {
    id: "d7-01",
    domain: 7,
    type: "theory",
    question: "Wat is tijdens incident response de eerste prioriteit wanneer mensen direct gevaar lopen?",
    options: ["Forensisch bewijs veiligstellen", "Beschikbaarheid herstellen", "Menselijke veiligheid beschermen", "De pers informeren"],
    correctIndex: 2,
    explanation: "Bescherming van mensenlevens en fysieke veiligheid gaat vóór systemen, data en bewijs.",
  },
  {
    id: "d7-02",
    domain: 7,
    type: "case",
    question: "Een server is vermoedelijk gehackt. Het team wil bewijs later juridisch kunnen gebruiken. Wat is essentieel?",
    options: ["De server direct formatteren", "Een gedocumenteerde chain of custody onderhouden", "Alle logs per e-mail versturen", "De verdachte informeren"],
    correctIndex: 1,
    explanation: "Chain of custody documenteert wie bewijs wanneer heeft verzameld, beheerd en overgedragen en ondersteunt de betrouwbaarheid ervan.",
  },
  {
    id: "d7-03",
    domain: 7,
    type: "theory",
    question: "Welke waarde beschrijft de maximaal aanvaardbare hoeveelheid dataverlies uitgedrukt in tijd?",
    options: ["MTTR", "RTO", "RPO", "SLA"],
    correctIndex: 2,
    explanation: "Recovery Point Objective bepaalt tot welk moment data hersteld moet kunnen worden en dus hoeveel dataverlies acceptabel is.",
  },
  {
    id: "d7-04",
    domain: 7,
    type: "case",
    question: "Een SOC ziet duizenden mislukte logins gevolgd door één succesvolle login vanaf hetzelfde adres. Wat is de beste eerste actie?",
    options: ["Het signaal negeren", "Het account en de bron onderzoeken en zo nodig direct beperken", "Alle auditlogs verwijderen", "De wachtwoordregels uitschakelen"],
    correctIndex: 1,
    explanation: "Dit patroon kan op brute force wijzen. Valideer het incident, beperk mogelijke schade en behoud relevante logs.",
  },
  {
    id: "d7-05",
    domain: 7,
    type: "theory",
    question: "Waarom moeten back-ups periodiek worden teruggezet in een test?",
    options: ["Om compressie te verhogen", "Om herstelbaarheid en de herstelprocedure te valideren", "Om retentie te omzeilen", "Om alle productie-incidenten te voorkomen"],
    correctIndex: 1,
    explanation: "Een geslaagde back-uptaak bewijst niet dat data bruikbaar teruggezet kan worden. Restore-tests leveren dat bewijs.",
  },
  {
    id: "d8-01",
    domain: 8,
    type: "theory",
    question: "In welke SDLC-fase is het doorgaans het goedkoopst om beveiligingseisen en threat modeling toe te passen?",
    options: ["Planning en ontwerp", "Na productie-implementatie", "Alleen tijdens incident response", "Na uitfasering"],
    correctIndex: 0,
    explanation: "Vroege beveiligingseisen en threat modeling voorkomen dure herontwerpen en reparaties later in de levenscyclus.",
  },
  {
    id: "d8-02",
    domain: 8,
    type: "case",
    question: "Een applicatie bouwt een SQL-query door gebruikersinvoer direct aan een tekenreeks toe te voegen. Welke maatregel is het meest effectief?",
    options: ["Meer logging", "Parameterized queries gebruiken", "De databasepoort wijzigen", "Uitvoer comprimeren"],
    correctIndex: 1,
    explanation: "Parameterized queries scheiden code van data en zijn een primaire verdediging tegen SQL-injectie.",
  },
  {
    id: "d8-03",
    domain: 8,
    type: "theory",
    question: "Wat is het doel van static application security testing (SAST)?",
    options: [
      "Een draaiende applicatie via netwerkverkeer testen",
      "Broncode of gecompileerde code analyseren zonder de applicatie uit te voeren",
      "Alleen open-source licenties controleren",
      "Productiegebruikers monitoren",
    ],
    correctIndex: 1,
    explanation: "SAST analyseert code of binaries zonder de applicatie als actief systeem te benaderen.",
  },
  {
    id: "d8-04",
    domain: 8,
    type: "case",
    question: "Een team neemt een populaire open-source bibliotheek op. Welke actie beheerst supply-chainrisico het best?",
    options: [
      "Alleen de downloadteller controleren",
      "Versie vastzetten, herkomst verifiëren en continu op kwetsbaarheden scannen",
      "De bibliotheek nooit bijwerken",
      "De naam van het pakket wijzigen",
    ],
    correctIndex: 1,
    explanation: "Herkomstcontrole, dependency locking, inventarisatie en continue kwetsbaarheidsbewaking beperken software supply-chainrisico.",
  },
  {
    id: "d8-05",
    domain: 8,
    type: "theory",
    question: "Welke test richt zich op een draaiende webapplicatie zonder de broncode rechtstreeks te analyseren?",
    options: ["SAST", "DAST", "Code review", "Compiler linting"],
    correctIndex: 1,
    explanation: "Dynamic Application Security Testing test de actieve applicatie van buitenaf via de beschikbare interfaces.",
  },
];

export const EXAM_QUESTION_COUNT = examQuestions.length;

export function calculateExamScore(answers: Record<string, number>) {
  return examQuestions.reduce(
    (score, question) => score + (answers[question.id] === question.correctIndex ? 1 : 0),
    0,
  );
}
