services:
  kali:
    build:
      context: ./kali
    container_name: kali-scanner
    hostname: kali-scanner
    tty: true
    stdin_open: true
    depends_on:
      - target
    networks:
      labnet:
        ipv4_address: 172.28.0.10
    cap_add:
      - NET_RAW
      - NET_ADMIN
    command: /bin/bash

  target:
    build:
      context: ./target
    container_name: linux-target
    hostname: linux-target
    networks:
      labnet:
        ipv4_address: 172.28.0.20
    expose:
      - "22"
      - "80"

networks:
  labnet:
    driver: bridge
    internal: true
    ipam:
      config:
        - subnet: 172.28.0.0/24
